[0.556s] Invoking command in '/home/siddhant/mrt_ws/build/custommsgsrv': CMAKE_PREFIX_PATH=/opt/ros/humble /usr/bin/cmake --build /home/siddhant/mrt_ws/build/custommsgsrv -- -j4 -l4
[0.606s] -- Found ament_cmake: 1.3.10 (/opt/ros/humble/share/ament_cmake/cmake)
[0.866s] -- Found geometry_msgs: 4.2.4 (/opt/ros/humble/share/geometry_msgs/cmake)
[0.926s] -- Found rosidl_generator_c: 3.1.5 (/opt/ros/humble/share/rosidl_generator_c/cmake)
[0.931s] -- Found rosidl_adapter: 3.1.5 (/opt/ros/humble/share/rosidl_adapter/cmake)
[0.942s] -- Found rosidl_generator_cpp: 3.1.5 (/opt/ros/humble/share/rosidl_generator_cpp/cmake)
[0.961s] -- Using all available rosidl_typesupport_c: rosidl_typesupport_fastrtps_c;rosidl_typesupport_introspection_c
[0.984s] -- Using all available rosidl_typesupport_cpp: rosidl_typesupport_fastrtps_cpp;rosidl_typesupport_introspection_cpp
[1.059s] -- Found rosidl_default_generators: 1.2.0 (/opt/ros/humble/share/rosidl_default_generators/cmake)
[1.469s] [31mCMake Error at /opt/ros/humble/share/rosidl_adapter/cmake/rosidl_adapt_interfaces.cmake:59 (message):
[1.469s]   execute_process(/usr/bin/python3 -m rosidl_adapter --package-name
[1.469s]   custommsgsrv --arguments-file
[1.470s]   /home/siddhant/mrt_ws/build/custommsgsrv/rosidl_adapter__arguments__custommsgsrv.json
[1.470s]   --output-dir
[1.470s]   /home/siddhant/mrt_ws/build/custommsgsrv/rosidl_adapter/custommsgsrv
[1.470s]   --output-file
[1.470s]   /home/siddhant/mrt_ws/build/custommsgsrv/rosidl_adapter/custommsgsrv.idls)
[1.470s]   returned error code 1:
[1.471s] 
[1.471s]   Error processing 'int64 Num' of 'custommsgsrv/Num': ''Num' is an invalid
[1.471s]   field name.  It should have the pattern
[1.471s]   '^(?!.*__)(?!.*_$)[a-z][a-z0-9_]*$''
[1.472s] 
[1.472s]   Traceback (most recent call last):
[1.472s] 
[1.472s]     File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
[1.472s]       return _run_code(code, main_globals, None,
[1.472s]     File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
[1.473s]       exec(code, run_globals)
[1.473s]     File "/opt/ros/humble/local/lib/python3.10/dist-packages/rosidl_adapter/__main__.py", line 19, in <module>
[1.473s]       sys.exit(main())
[1.473s]     File "/opt/ros/humble/local/lib/python3.10/dist-packages/rosidl_adapter/main.py", line 53, in main
[1.473s]       abs_idl_file = convert_to_idl(
[1.473s]     File "/opt/ros/humble/local/lib/python3.10/dist-packages/rosidl_adapter/__init__.py", line 19, in convert_to_idl
[1.474s]       return convert_msg_to_idl(
[1.474s]     File "/opt/ros/humble/local/lib/python3.10/dist-packages/rosidl_adapter/msg/__init__.py", line 28, in convert_msg_to_idl
[1.474s]       msg = parse_message_string(package_name, input_file.stem, content)
[1.474s]     File "/opt/ros/humble/local/lib/python3.10/dist-packages/rosidl_adapter/parser.py", line 519, in parse_message_string
[1.474s]       fields.append(Field(
[1.475s]     File "/opt/ros/humble/local/lib/python3.10/dist-packages/rosidl_adapter/parser.py", line 354, in __init__
[1.475s]       raise NameError(
[1.475s] 
[1.475s]   NameError: 'Num' is an invalid field name.  It should have the pattern
[1.475s]   '^(?!.*__)(?!.*_$)[a-z][a-z0-9_]*$'
[1.475s] 
[1.475s] Call Stack (most recent call first):
[1.476s]   /opt/ros/humble/share/rosidl_cmake/cmake/rosidl_generate_interfaces.cmake:130 (rosidl_adapt_interfaces)
[1.476s]   CMakeLists.txt:13 (rosidl_generate_interfaces)
[1.476s] 
[1.477s] [0m
[1.478s] -- Configuring incomplete, errors occurred!
[1.478s] See also "/home/siddhant/mrt_ws/build/custommsgsrv/CMakeFiles/CMakeOutput.log".
[1.491s] gmake: *** [Makefile:226: cmake_check_build_system] Error 1
[1.499s] Invoked command in '/home/siddhant/mrt_ws/build/custommsgsrv' returned '2': CMAKE_PREFIX_PATH=/opt/ros/humble /usr/bin/cmake --build /home/siddhant/mrt_ws/build/custommsgsrv -- -j4 -l4
